services:
  # Catto Service
  catto_service:
    container_name: catto_service
    build: .
    environment:
      PQ_HOST: postgres
      PQ_PORT: 5432
      PQ_USERNAME: ${PQ_USERNAME}
      PQ_PASSWORD: ${PQ_PASSWORD}
      PQ_DB: ${PQ_DB}
    ports:
      - 8080:8080
  # PG DB
  postgres:
    container_name: catto_postgres
    image: postgres:14.3-alpine3.16
    restart: always
    environment:
      POSTGRES_USER: ${PQ_USERNAME}
      POSTGRES_PASSWORD: ${PQ_PASSWORD}
      POSTGRES_DB: ${PQ_DB}
    ports:
      - ${PQ_PORT}:5432
